image: registry.gitlab.com/mtdelotavo/apigee_automation:latest

build:
  stage: build
  when: manual
  script:
    - apigeetool deployproxy --verbose --organization $APIGEE_ORG --username $APIGEE_USER --password $APIGEE_PASSWORD --environments test --api helloworld --directory api-proxies/helloworld/
